/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasi.objek.wisata;

import aplikasi.objek.wisata.fungsi;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author Asus
 */
public class absensi extends javax.swing.JFrame {
    String SQL = "SELECT * FROM absensi";
    String[] field = {"tgl","nama_petugas","shift","jabatan","jam_masuk","jam_pulang"};

    /**
     * Creates new form absensi
     */
    public absensi() {
        fungsi absensi=new fungsi();
        initComponents();
        this.setLocationRelativeTo(null);
        absensi.settingJudulTabel(table_absen, field);
        absensi.tampilTabel(table_absen, SQL, field);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nama_ptgs = new javax.swing.JLabel();
        shift = new javax.swing.JLabel();
        jabatan = new javax.swing.JLabel();
        jam_masuk = new javax.swing.JLabel();
        jam_pulang = new javax.swing.JLabel();
        tgl = new javax.swing.JLabel();
        txtnama_ptgs = new javax.swing.JTextField();
        txtjam_masuk = new javax.swing.JTextField();
        txtjam_pulang = new javax.swing.JTextField();
        btn_save = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();
        btn_update = new javax.swing.JButton();
        btn_del = new javax.swing.JButton();
        cetakdata = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_absen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel7.setFont(new java.awt.Font("Yu Gothic Medium", 1, 18)); // NOI18N
        jLabel7.setText("ABSENSI PETUGAS");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(353, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(306, 306, 306))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel7)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        nama_ptgs.setText("Nama Petugas :");

        shift.setText("Shift  :");

        jabatan.setText("Jabatan  :");

        jam_masuk.setText("Jam Masuk  :");

        jam_pulang.setText("Jam Pulang  :");

        tgl.setText("Tanggal :");

        txtjam_masuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjam_masukActionPerformed(evt);
            }
        });

        txtjam_pulang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjam_pulangActionPerformed(evt);
            }
        });

        btn_save.setText("Save");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_batal.setText("Clear");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        btn_update.setText("Update");
        btn_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updateActionPerformed(evt);
            }
        });

        btn_del.setText("Delete");
        btn_del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_delActionPerformed(evt);
            }
        });

        cetakdata.setText("Cetak Data");
        cetakdata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakdataActionPerformed(evt);
            }
        });

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pagi", "Malam" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pimpinan", "Wakil Pimpinan", "Sekretaris ", "Bendahara", "Karyawan", "Satpam", "Tim Medis", " " }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jabatan)
                            .addComponent(jam_masuk))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjam_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_batal)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nama_ptgs)
                                .addComponent(tgl)
                                .addComponent(shift))
                            .addComponent(btn_save))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtnama_ptgs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btn_del)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jam_pulang)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                                    .addComponent(btn_update))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addComponent(txtjam_pulang))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(cetakdata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(kembali)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tgl)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nama_ptgs)
                            .addComponent(txtnama_ptgs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shift)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jabatan)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jam_masuk)
                            .addComponent(txtjam_masuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jam_pulang)
                            .addComponent(txtjam_pulang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_batal)
                            .addComponent(btn_update))
                        .addGap(6, 6, 6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cetakdata)
                    .addComponent(kembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save)
                    .addComponent(btn_del))
                .addGap(42, 42, 42))
        );

        table_absen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_absen.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_absenMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_absen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_delActionPerformed
        // TODO add your handling code here:
//        String[] var = {"Tanggal","Nama_Petugas","Shift","Jabatan","Jam_Masuk","Jam_Pulang"};
//        String[] isi = {txttgl.getText(),txtnama_ptgs.getText(),txtshift.getText(),txtjabatan.getText(),txtjam_masuk.getText(),txtjam_pulang.getText()};
        try{
            new fungsi().Delete("absensi", "nama_petugas", txtnama_ptgs.getText());
            JOptionPane.showMessageDialog(null, "Data berhasil Dihapus");
            new fungsi().settingJudulTabel(table_absen, field);
            new fungsi().tampilTabel(table_absen, SQL, field);
            jDateChooser1.setCalendar(null);
            txtnama_ptgs.setText("");
            jComboBox1.setSelectedItem("");
            jComboBox2.setSelectedItem("");
            txtjam_masuk.setText("");
            txtjam_pulang.setText("");
        } catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btn_delActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        // TODO add your handling code here:
        jDateChooser1.setCalendar(null);
        txtnama_ptgs.setText("");
        jComboBox1.setSelectedItem("");
        jComboBox2.setSelectedItem("");
        txtjam_masuk.setText("");
        txtjam_pulang.setText("");
    }//GEN-LAST:event_btn_batalActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        String date = "yyyy-MM-dd";
        SimpleDateFormat format = new SimpleDateFormat(date);
        String tanggal = String.valueOf(format.format(jDateChooser1.getDate()));
        try {

            if(jDateChooser1.getDate().equals("")){
                JOptionPane.showMessageDialog(null, "Tanggal Belum Terisi");
            }else if(txtnama_ptgs.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Nama Petugas Belum Terisi");
                txtnama_ptgs.requestFocus();
            } else if(jComboBox1.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(null, "Shift Belum Terisi");
                jComboBox1.requestFocus();
            } else if(jComboBox2.getSelectedItem().equals("")){
                JOptionPane.showMessageDialog(null, "Jabatan Belum Terisi");
                jComboBox2.requestFocus();
            } else if(txtjam_masuk.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Jam Masuk Belum Terisi");
                txtjam_masuk.requestFocus();
            } else if(txtjam_pulang.getText().trim().equals("")){
                JOptionPane.showMessageDialog(null, "Jam Pulang Belum Terisi");
                txtjam_pulang.requestFocus();
            } else {
                String[] field = {"tgl","nama_petugas","shift","jabatan","jam_masuk","jam_pulang"};
                String[] var = {"Tanggal","Nama_Petugas","Shift","Jabatan","Jam_Masuk","Jam_Pulang"};
                String[] isi = {tanggal,txtnama_ptgs.getText(),(String) jComboBox1.getSelectedItem(),(String) jComboBox2.getSelectedItem(),txtjam_masuk.getText(),txtjam_pulang.getText()};
                new fungsi().SimpanDinamis("absensi", field, isi);
                new fungsi().settingJudulTabel(table_absen,var );
                new fungsi().tampilTabel(table_absen,SQL, var);
            }
        } catch (Exception e){
            System.out.println(e.toString());
        }

    }//GEN-LAST:event_btn_saveActionPerformed

    private void txtjam_pulangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjam_pulangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjam_pulangActionPerformed

    private void txtjam_masukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjam_masukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjam_masukActionPerformed

    private void btn_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updateActionPerformed
        // TODO add your handling code here:
        String date = "yyyy-MM-dd";
            SimpleDateFormat format = new SimpleDateFormat(date);
            String tanggal = String.valueOf(format.format(jDateChooser1.getDate()));
        try{
            String sql = "UPDATE absensi SET tgl = '"+tanggal+"', nama_petugas = '"+txtnama_ptgs.getText()+"', shift = '"+(String) jComboBox1.getSelectedItem()+"',jabatan= '"+jComboBox2.getSelectedItem()+"',jam_masuk= '"+txtjam_masuk.getText()+"',jam_pulang= '"+txtjam_pulang.getText()+"' WHERE nama_petugas = '"+txtnama_ptgs.getText()+"'";
            Connection koneksi=(Connection)fungsi.koneksidb();
            PreparedStatement st=koneksi.prepareStatement(sql);
            st.executeUpdate();
            new fungsi().settingJudulTabel(table_absen, field);
            new fungsi().tampilTabel(table_absen, SQL, field);
            JOptionPane.showMessageDialog(null, "Data Berhasil diubah");
        } catch (Exception e){
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_btn_updateActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
       new Utama().setVisible(true);
                //menutup gui login
                this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void table_absenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_absenMouseClicked
        // TODO add your handling code here:
        int row = table_absen.getSelectedRow();
        jDateChooser1.setDate(new fungsi().getTanggalTabel(table_absen,0));
        txtnama_ptgs.setText(table_absen.getModel().getValueAt(row,1).toString());
        jComboBox1.setSelectedItem(table_absen.getModel().getValueAt(row,2).toString());
        jComboBox2.setSelectedItem(table_absen.getModel().getValueAt(row,3).toString());
        txtjam_masuk.setText(table_absen.getModel().getValueAt(row,4).toString());
        txtjam_pulang.setText(table_absen.getModel().getValueAt(row,5).toString());
    }//GEN-LAST:event_table_absenMouseClicked

    private void cetakdataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakdataActionPerformed
        // TODO add your handling code here:
        try{
            HashMap parameter = new HashMap ();
            Class.forName("com.mysql.jdbc.Driver");
            Connection cn = (Connection)fungsi.koneksidb();
            File file = new File("src/Laporan/LaporanAbsensi.jasper");
            JasperReport jr = (JasperReport)JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, cn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch(Exception e){
            javax.swing.JOptionPane.showMessageDialog(null, "Data Tidak Dapat di Cetak!!" + "\n"+ e.getMessage(),"cetak Data", javax.swing.JOptionPane.ERROR_MESSAGE);
        } 
    }//GEN-LAST:event_cetakdataActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new absensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_del;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cetakdata;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jabatan;
    private javax.swing.JLabel jam_masuk;
    private javax.swing.JLabel jam_pulang;
    private javax.swing.JButton kembali;
    private javax.swing.JLabel nama_ptgs;
    private javax.swing.JLabel shift;
    private javax.swing.JTable table_absen;
    private javax.swing.JLabel tgl;
    private javax.swing.JTextField txtjam_masuk;
    private javax.swing.JTextField txtjam_pulang;
    private javax.swing.JTextField txtnama_ptgs;
    // End of variables declaration//GEN-END:variables
}
